# Generated by Django 6.0.3 on 2026-04-02 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_application_essay_application_motivation_letter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True, verbose_name='Логин')),
                ('password_hash', models.CharField(max_length=255, verbose_name='Хэш пароля')),
                ('name', models.CharField(max_length=200, verbose_name='Имя преподавателя')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Учитель',
                'verbose_name_plural': 'Учителя',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='ФИО Ученика')),
                ('date_added', models.DateTimeField(auto_now_add=True, verbose_name='Дата добавления')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='candidates.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Ученик учителя',
                'verbose_name_plural': 'Ученики учителей',
            },
        ),
        migrations.CreateModel(
            name='TeacherProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок предложения')),
                ('message', models.TextField(verbose_name='Текст предложения')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposals', to='candidates.teacher', verbose_name='Учитель')),
            ],
            options={
                'verbose_name': 'Предложение для учителя',
                'verbose_name_plural': 'Предложения для учителей',
                'ordering': ['-created_at'],
            },
        ),
    ]
