[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn invision.wsgi --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
