version: "3.9"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_DB: invision_u
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  bot:
    build: .
    restart: always
    depends_on:
      - db
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: invision_u
      DB_USER: postgres
      DB_PASS: postgres
    volumes:
      - ./:/app

volumes:
  pgdata:
